### ISSUE TITLE
Error when running JSDoc

### ISSUE THREAD

**Issue by bandantonio** [layoutzweb/jsdoc-chameleon-template#1]
Hello,
I'm trying to use this template, but when running jsdoc the following error occurs:

```
undefined:8
var usesSearch = Boolean(template.search);
                                  ^

TypeError: Cannot read property 'search' of undefined
    at exports.Template.eval (eval at _.template (/home/john_doe/test.git/jsdoc/node_modules/underscore/underscore.js:1454:20), <anonymous>:8:35)
    at exports.Template.template (/home/john_doe/test.git/jsdoc/node_modules/underscore/underscore.js:1461:21)
    at exports.Template.partial (/home/john_doe/test.git/jsdoc/node_modules/jsdoc/lib/jsdoc/template.js:55:29)
    at exports.Template.render (/home/john_doe/test.git/jsdoc/node_modules/jsdoc/lib/jsdoc/template.js:74:24)
    at generate (/home/john_doe/test.git/jsdoc/node_modules/jsdoc-chameleon-template/publish.js:207:19)
    at /home/john_doe/test.git/jsdoc/node_modules/jsdoc-chameleon-template/publish.js:234:5
    at Array.forEach (<anonymous>)
    at generateSourceFiles (/home/john_doe/test.git/jsdoc/node_modules/jsdoc-chameleon-template/publish.js:218:28)
    at Object.exports.publish (/home/john_doe/test.git/jsdoc/node_modules/jsdoc-chameleon-template/publish.js:576:5)
    at Object.module.exports.cli.generateDocs (/home/john_doe/test.git/jsdoc/node_modules/jsdoc/cli.js:448:35)
    at Object.module.exports.cli.processParseResults (/home/john_doe/test.git/jsdoc/node_modules/jsdoc/cli.js:399:20)
    at module.exports.cli.main (/home/john_doe/test.git/jsdoc/node_modules/jsdoc/cli.js:240:14)
    at Object.module.exports.cli.runCommand (/home/john_doe/test.git/jsdoc/node_modules/jsdoc/cli.js:189:5)
    at /home/john_doe/test.git/jsdoc/node_modules/jsdoc/jsdoc.js:105:9
    at Object.<anonymous> (/home/john_doe/test.git/jsdoc/node_modules/jsdoc/jsdoc.js:106:3)
    at Module._compile (module.js:652:30)
```

My jsdoc.json:

```
{
    "source": {
        "include": [
            "src/test.js",
            "src/README.md"
        ],
        "includePattern": ".+\\.js(doc|x)?$"
    },
    "recurseDepth": 5,
    "plugins": [
        "plugins/markdown"
    ],
    "markdown": {
        "idInHeadings": true
    },
    "opts": {
        "template": "node_modules/jsdoc-chameleon-template",
        "destination": "./out"
    },
    "templates": {
        "cleverLinks": false,
        "monospaceLinks": true,
        "useLongnameInNav": false,
        "showInheritedInNav": true,
        "default": {
            "includeDate": false
        }
    }
}
```

package.json script:

```
"jsdoc": "./node_modules/.bin/jsdoc -c jsdoc.json"
```

It seems that something wrong with the template or I missed something to install. Any help?

**Comment by bandantonio** [comment]
Fixed it by copy-pasting the [example](../#example-jsdoc-config) JSDoc config file
